#!/usr/bin/env python3
"""
X (@ntv_rd) -> Instagram (tokyoprototye.jp) auto cross-post.

Runs hourly on GitHub Actions.
- Fetches recent original posts from X (Owned Reads)
- Skips posts already on Instagram (dedupe via X post URL embedded in IG caption)
- Videos: center-crop to 9:16 full screen, logo top-left, small title at top,
  Japanese telop lines at the bottom (generated by Claude), posted as Reels
- Images: posted as-is (16:9 is within IG feed limits), carousel if multiple
- Caption: original JA text + natural EN translation + X post URL
"""
import json
import os
import subprocess
import sys
import tempfile
import time
import urllib.parse
import urllib.request

X_BEARER = os.environ["X_BEARER_TOKEN"]
IG_TOKEN = os.environ["IG_ACCESS_TOKEN"]
ANTHROPIC_KEY = os.environ.get("ANTHROPIC_API_KEY", "")
GEMINI_KEY = os.environ.get("GEMINI_API_KEY", "")
DEEPL_KEY = os.environ.get("DEEPL_API_KEY", "")
GH_REPO = os.environ.get("GITHUB_REPOSITORY", "")
GH_PAT = os.environ.get("GH_PAT", os.environ.get("GITHUB_TOKEN", ""))
X_USERNAME = os.environ.get("X_USERNAME", "ntv_rd")
DRY_RUN = os.environ.get("DRY_RUN", "false").lower() == "true"
MAX_POSTS_PER_RUN = int(os.environ.get("MAX_POSTS_PER_RUN", "3"))
LOOKBACK = int(os.environ.get("LOOKBACK_TWEETS", "10"))

FONT = "/usr/share/fonts/opentype/noto/NotoSansCJK-Bold.ttc"
GRAPH = "https://graph.instagram.com/v23.0"


def http(url, method="GET", headers=None, data=None, timeout=120):
    req = urllib.request.Request(url, method=method, headers=headers or {})
    body = None
    if data is not None:
        if isinstance(data, dict):
            body = urllib.parse.urlencode(data).encode()
        else:
            body = data
    try:
        with urllib.request.urlopen(
            urllib.request.Request(url, data=body, method=method, headers=headers or {}),
            timeout=timeout,
        ) as r:
            return json.loads(r.read().decode())
    except urllib.error.HTTPError as e:
        detail = ""
        try:
            detail = e.read().decode()[:1000]
        except Exception:
            pass
        raise RuntimeError(f"HTTP {e.code} for {url.split('?')[0]}: {detail}") from None


def x_api(path, params):
    url = f"https://api.x.com/2/{path}?{urllib.parse.urlencode(params)}"
    return http(url, headers={"Authorization": f"Bearer {X_BEARER}"})


def claude(prompt, max_tokens=2000):
    body = json.dumps({
        "model": "claude-sonnet-4-5",
        "max_tokens": max_tokens,
        "messages": [{"role": "user", "content": prompt}],
    }).encode()
    r = http(
        "https://api.anthropic.com/v1/messages",
        method="POST",
        headers={
            "x-api-key": ANTHROPIC_KEY,
            "anthropic-version": "2023-06-01",
            "content-type": "application/json",
        },
        data=body,
    )
    return r["content"][0]["text"]


def gemini(prompt):
    body = json.dumps({
        "contents": [{"parts": [{"text": prompt}]}],
        "generationConfig": {"temperature": 0.4},
    }).encode()
    last_err = None
    for model in ("gemini-flash-latest", "gemini-2.5-flash", "gemini-2.0-flash"):
        for attempt in range(2):
            try:
                r = http(
                    "https://generativelanguage.googleapis.com/v1beta/models/"
                    f"{model}:generateContent",
                    method="POST",
                    headers={"content-type": "application/json",
                             "x-goog-api-key": GEMINI_KEY},
                    data=body)
                return r["candidates"][0]["content"]["parts"][0]["text"]
            except RuntimeError as e:
                last_err = e
                if "HTTP 429" in str(e) and attempt == 0:
                    time.sleep(20)
                else:
                    break
    raise last_err


def deepl_translate(text):
    r = http("https://api-free.deepl.com/v2/translate", method="POST",
             headers={"Authorization": f"DeepL-Auth-Key {DEEPL_KEY}"},
             data={"text": text, "source_lang": "JA", "target_lang": "EN-US"})
    return r["translations"][0]["text"]


def generate_copy(tweet_text):
    """Generate title, telop lines and bilingual caption. Returns dict."""
    if not (ANTHROPIC_KEY or GEMINI_KEY):
        if DEEPL_KEY:
            return {"title_line1": "", "title_line2": "", "telops": [],
                    "caption_ja": tweet_text,
                    "caption_en": deepl_translate(tweet_text)}
        raise RuntimeError("No translation API key configured")
    prompt = f"""あなたは日本テレビR&Dラボ(@ntv_rd)のSNS運用担当です。以下のXポストをInstagramリールに転記します。

Xポスト本文:
---
{tweet_text}
---

次のJSONだけを出力してください(コードブロック不要):
{{
  "title_line1": "動画上部に常時表示する小さめタイトル1行目(例: 作家名や作品名・イベント名。全角14文字以内)",
  "title_line2": "タイトル2行目(作品名の続きや会期など。不要なら空文字。全角28文字/半角56文字以内)",
  "telops": ["画面下部に順番に表示するテロップ。本文の要点を1行ずつ、各行 全角20文字以内、2〜5行"],
  "caption_ja": "Instagramキャプション日本語(本文をほぼそのまま。ハッシュタグがあれば残す)",
  "caption_en": "自然で簡潔な英訳(直訳調を避ける)"
}}"""
    txt = (claude(prompt) if ANTHROPIC_KEY else gemini(prompt)).strip()
    if txt.startswith("```"):
        txt = txt.strip("`").lstrip("json").strip()
    return json.loads(txt)


def ig_recent_captions():
    out = []
    url = f"{GRAPH}/me/media?fields=caption&limit=50&access_token={IG_TOKEN}"
    r = http(url)
    for m in r.get("data", []):
        out.append(m.get("caption") or "")
    return out


def pick_video_variant(media):
    best, best_br = None, -1
    for v in media.get("variants", []):
        if v.get("content_type") == "video/mp4" and v.get("bit_rate", 0) > best_br:
            best, best_br = v["url"], v["bit_rate"]
    return best


def ffmpeg_edit(src, dst, copy):
    """Center-crop to 9:16 full-screen, logo top-left, small title, timed telops."""
    dur = float(subprocess.check_output(
        ["ffprobe", "-v", "error", "-show_entries", "format=duration",
         "-of", "csv=p=0", src]).decode().strip())
    telops = [t for t in copy.get("telops", []) if t.strip()][:6] or ["　"]
    seg = dur / len(telops)

    def esc(s):
        return s.replace("\\", "\\\\").replace(":", "\\:").replace("'", "\\\\\\'")

    chains = [
        "[0:v]crop=ih*9/16:ih,scale=1080:1920[v]",
        "[1:v]scale=170:170[logo]",
        "[v][logo]overlay=48:48[b]",
    ]
    dt = []
    t1 = copy.get("title_line1", "").strip()
    t2 = copy.get("title_line2", "").strip()
    if t1:
        dt.append(f"drawtext=fontfile={FONT}:text='{esc(t1)}':fontcolor=white:"
                  f"fontsize=36:borderw=4:bordercolor=black@0.8:x=240+(790-text_w)/2:y=78")
    if t2:
        dt.append(f"drawtext=fontfile={FONT}:text='{esc(t2)}':fontcolor=white:"
                  f"fontsize=27:borderw=4:bordercolor=black@0.8:x=240+(790-text_w)/2:y=136")
    for i, tl in enumerate(telops):
        a, b = i * seg, (i + 1) * seg + (0.5 if i == len(telops) - 1 else 0)
        size = 48 if len(tl) <= 15 else 44
        dt.append(f"drawtext=fontfile={FONT}:text='{esc(tl)}':fontcolor=white:"
                  f"fontsize={size}:borderw=6:bordercolor=black@0.85:"
                  f"x=(w-text_w)/2:y=1610:enable='between(t,{a:.2f},{b:.2f})'")
    fc = ";".join(chains[:-1]) + ";" + chains[-1].replace("[b]", "[b];[b]" + ",".join(dt) + ",format=yuv420p")
    subprocess.check_call([
        "ffmpeg", "-y", "-v", "error", "-i", src, "-i", "assets/logo.png",
        "-filter_complex", fc, "-c:v", "libx264", "-preset", "fast", "-crf", "23",
        "-c:a", "aac", "-b:a", "128k", "-movflags", "+faststart", dst])


def gh_release_upload(path, tag):
    """Upload file as a release asset on this (public) repo; return download URL."""
    api = f"https://api.github.com/repos/{GH_REPO}"
    h = {"Authorization": f"Bearer {GH_PAT}", "Accept": "application/vnd.github+json"}
    try:
        rel = http(f"{api}/releases/tags/{tag}", headers=h)
    except Exception:
        rel = http(f"{api}/releases", method="POST", headers=h,
                   data=json.dumps({"tag_name": tag, "name": tag,
                                    "body": "auto media hosting"}).encode())
    up = rel["upload_url"].split("{")[0] + f"?name={os.path.basename(path)}"
    with open(path, "rb") as f:
        data = f.read()
    asset = http(up, method="POST", data=data,
                 headers={**h, "Content-Type": "video/mp4"})
    return asset["browser_download_url"]


def ig_create_and_publish(params):
    r = http(f"{GRAPH}/me/media", method="POST", data={**params, "access_token": IG_TOKEN})
    cid = r["id"]
    for _ in range(60):  # wait for processing
        st = http(f"{GRAPH}/{cid}?fields=status_code&access_token={IG_TOKEN}")
        if st.get("status_code") == "FINISHED":
            break
        if st.get("status_code") == "ERROR":
            raise RuntimeError(f"IG container error: {st}")
        time.sleep(10)
    pub = http(f"{GRAPH}/me/media_publish", method="POST",
               data={"creation_id": cid, "access_token": IG_TOKEN})
    return pub["id"]


def main():
    user = x_api(f"users/by/username/{X_USERNAME}", {})["data"]
    tweets = x_api(f"users/{user['id']}/tweets", {
        "max_results": LOOKBACK, "exclude": "replies,retweets",
        "expansions": "attachments.media_keys",
        "media.fields": "url,variants,type,media_key",
        "tweet.fields": "created_at,text,entities",
    })
    media_map = {m["media_key"]: m for m in tweets.get("includes", {}).get("media", [])}
    existing = " ".join(ig_recent_captions())
    posted = 0

    for tw in reversed(tweets.get("data", [])):  # oldest first
        url = f"https://x.com/{X_USERNAME}/status/{tw['id']}"
        if tw["id"] in existing:
            continue
        keys = tw.get("attachments", {}).get("media_keys", [])
        media = [media_map[k] for k in keys if k in media_map]
        if not media:
            print(f"skip (no media): {url}")
            continue
        if posted >= MAX_POSTS_PER_RUN:
            break
        print(f"processing: {url}")
        if ANTHROPIC_KEY or GEMINI_KEY or DEEPL_KEY:
            copy = generate_copy(tw["text"])
        else:
            print("NOTE: no translation API key set; using placeholder copy")
            copy = {"title_line1": "", "title_line2": "", "telops": [],
                    "caption_ja": tw["text"], "caption_en": "(EN translation pending)"}
        caption = f"{copy['caption_ja']}\n\n{copy['caption_en']}\n\n{url}"

        vids = [m for m in media if m["type"] in ("video", "animated_gif")]
        if DRY_RUN:
            print(json.dumps(copy, ensure_ascii=False, indent=2))
            print("DRY_RUN: not posting")
            posted += 1
            continue
        if vids:
            src_url = pick_video_variant(vids[0])
            with tempfile.TemporaryDirectory() as td:
                src, dst = f"{td}/src.mp4", f"{td}/reel.mp4"
                urllib.request.urlretrieve(src_url, src)
                ffmpeg_edit(src, dst, copy)
                host_url = gh_release_upload(dst, f"media-{tw['id']}")
            ig_create_and_publish({"media_type": "REELS", "video_url": host_url,
                                   "caption": caption, "share_to_feed": "true"})
        else:
            imgs = [m["url"] for m in media if m["type"] == "photo"]
            if len(imgs) == 1:
                ig_create_and_publish({"image_url": imgs[0], "caption": caption})
            else:
                children = []
                for iu in imgs[:10]:
                    c = http(f"{GRAPH}/me/media", method="POST",
                             data={"image_url": iu, "is_carousel_item": "true",
                                   "access_token": IG_TOKEN})
                    children.append(c["id"])
                ig_create_and_publish({"media_type": "CAROUSEL",
                                       "children": ",".join(children),
                                       "caption": caption})
        print(f"posted: {url}")
        posted += 1

    print(f"done. posted={posted}")


if __name__ == "__main__":
    sys.exit(main())
